MarksMovies.RazorPagesUI/Pages/Movies/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarksMovies.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MarksMovies.TMDB;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class CreateModel : PageModel
    {
        private WebCreateService _service { get; set; }

        public CreateModel(WebCreateService Service)
        {
            _service = Service;
            Movie = new Movie();
            SearchMovies = new SearchMovies();
            MovieOrTVShowSelection = MovieOrTVShow.Movie;
            SearchTV = new SearchTV();
        }



        [BindProperty]
        public virtual Movie Movie { get; set; }

        [BindProperty]
        public virtual IList<GenreType> SelectedGenres { get; set; }

        public virtual SearchMovies SearchMovies { get; set; }

        public virtual SearchTV SearchTV { get; set; }

        [Display(Name = "Movie or Television?")]
        [BindProperty]
        public MovieOrTVShow MovieOrTVShowSelection { get; set; }


        public IActionResult OnGet()
        {
            return Page();
        }


        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Movie.MovieOrTVShow = MovieOrTVShowSelection;
            var MovieID = await _service.CreateAsync(Movie, SelectedGenres);


            return Redirect(Url.Content("~/Movies/Index") + "#" + MovieID);
        }




        public virtual async Task<IActionResult> OnPostFetchAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Movie.Title != string.Empty)
                if(MovieOrTVShowSelection == MovieOrTVShow.Movie)
                    SearchMovies = await _service.FetchMovieAsync(Movie.Title);
                else if(MovieOrTVShowSelection == MovieOrTVShow.TV)
                    SearchTV = await _service.FetchTVShowsAsync(Movie.Title);


            return Page();
        }



        public virtual async Task<IActionResult> OnPostImportAsync(int TMDB_ID)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            if (TMDB_ID > 0)
            {

                if (SelectedGenres.Count > 0)
                {
                    SelectedGenres.Clear();
                }

                if(MovieOrTVShowSelection == MovieOrTVShow.Movie)
                    Movie = await _service.ImportMovieAsync(TMDB_ID);
                else if(MovieOrTVShowSelection == MovieOrTVShow.TV)
                    Movie = await _service.ImportTVShowAsync(TMDB_ID);

                if (Movie?.Genres?.Count > 0)
                {
                    foreach (var g in Movie.Genres)
                    {
                        SelectedGenres.Add(g.genre);
                    }
                }
            }

            ModelState.Clear();

            return Page();

        }

    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MarksMovies.Models;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class DeleteModel : PageModel
    {
        private readonly WebDeleteService _service;

        public DeleteModel(WebDeleteService Service)
        {
            _service = Service;
            Movie = new Movie();
        }

        [BindProperty]
        public Movie Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            Movie = await _service.GetAsync(ID);

            if (Movie == null)
                return NotFound();
            else
                return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            if (await _service.DeleteMovieAsync(ID) == WebDeleteService.DELETE_FAIL)
                return NotFound();
            else
                return RedirectToPage("./Index");
        }
    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Details.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MarksMovies.Models;
using MarksMovies.TMDB;
using System.Linq;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class DetailsModel : PageModel
    {
        private readonly WebDetailsService _service;


        public DetailsModel(WebDetailsService Service)
        {
            _service = Service;
            Movie = new Movie();
            MovieDetails = new MovieDetails();
            TVDetails = new TVShowDetails();
        }

        public Movie Movie { get; set; }

        public string PosterURL { get; set; }

        public string Overview { get; set; }

        public string Tagline { get; set; }

        public int Runtime { get; set; }

        public int SeasonCount { get; set; }

        public MovieDetails MovieDetails {get;set;}

        public TVShowDetails TVDetails { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _service.GetAsync(id);

            if (Movie == null || Movie?.TMDB_ID <= 0)
                return NotFound();

            if (Movie.MovieOrTVShow == MovieOrTVShow.Movie)
            {
                MovieDetails = await _service.GetMovieDetailsAsync(Movie.TMDB_ID);

                if (MovieDetails != null)
                {
                    PosterURL = "https://image.tmdb.org/t/p/w185" + MovieDetails.poster_path;
                    Overview = MovieDetails.overview;
                    Tagline = MovieDetails.tagline;
                    Runtime = MovieDetails.runtime;
                }
            } else if (Movie.MovieOrTVShow == MovieOrTVShow.TV)
            {
                TVDetails = await _service.GetTVSHowDetailsAsync(Movie.TMDB_ID);

                if (TVDetails == null)
                    return Page();
                
                Overview = TVDetails.overview;
                PosterURL = "https://image.tmdb.org/t/p/w185" + TVDetails.poster_path;

                foreach (var season in TVDetails.seasons)
                {
                    if (season.season_number == Movie.Season)
                    {
                        if(!string.IsNullOrEmpty(season.poster_path))
                            PosterURL = "https://image.tmdb.org/t/p/w185" + season.poster_path;
                        if(!string.IsNullOrEmpty(season.overview))
                            Overview = season.overview;
                        break;
                    }
                }

                Tagline = string.Empty;

                SeasonCount = TVDetails.number_of_seasons;

                if (TVDetails.episode_run_time?.Count() > 0)
                    Runtime = TVDetails.episode_run_time.ToList().FirstOrDefault();
            }
            
            return Page();
        }
    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MarksMovies.Models;
using System.ComponentModel.DataAnnotations;
using MarksMovies.TMDB;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class EditModel : PageModel
    {
        private readonly WebEditService _service;

        public EditModel(WebEditService Service)
        {
            _service = Service;
            SearchMovies = new SearchMovies();
            SearchTV = new SearchTV();
            Movie = new Movie();
            SelectedGenres = new List<GenreType>();
        }

        public SearchMovies SearchMovies { get; set; }

        public SearchTV SearchTV { get; set; }

        [BindProperty]
        public Movie Movie { get; set; }

        [BindProperty]
        public IList<GenreType> SelectedGenres { get; set; }

        [Display(Name = "Movie or Television?")]
        [BindProperty]
        public MovieOrTVShow MovieOrTVShowSelection { get; set; }


        

        public async Task<IActionResult> OnGetAsync(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            Movie = await _service.GetAsync(ID);

            if (Movie == null)
                return NotFound();

            MovieOrTVShowSelection = Movie.MovieOrTVShow;

            foreach (var mg in Movie.Genres)
            {
                SelectedGenres.Add(mg.genre);
            }
            
            return Page();
        }



        public async Task<IActionResult> OnPostEditAsync(int? ID)
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            Movie.MovieOrTVShow = MovieOrTVShowSelection;
            await _service.SaveMovieAsync(Movie, SelectedGenres);

            return Redirect(Url.Content("~/Movies/Index") + "#" + ID);
        }


        public virtual async Task<IActionResult> OnPostFetchAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Movie.Title != string.Empty)
            {
                if (MovieOrTVShowSelection == MovieOrTVShow.Movie)
                    SearchMovies = await _service.FetchMovieAsync(Movie.Title);
                else if (MovieOrTVShowSelection == MovieOrTVShow.TV)
                    SearchTV = await _service.FetchTVShowsAsync(Movie.Title);
            }
            return Page();
        }



        public virtual async Task<IActionResult> OnPostImportAsync(int TMDB_ID)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            if (TMDB_ID > 0)
            {
                if (SelectedGenres.Count > 0)
                {
                    SelectedGenres.Clear();
                }

                if(MovieOrTVShowSelection == MovieOrTVShow.Movie)
                    Movie = await _service.ImportMovieAsync(TMDB_ID);
                else if(MovieOrTVShowSelection == MovieOrTVShow.TV)
                    Movie = await _service.ImportTVShowAsync(TMDB_ID);

                foreach (var g in Movie.Genres)
                {
                    SelectedGenres.Add(g.genre);
                }
            }

            ModelState.Clear();

            return Page();

        }
    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Export.cshtml.cs
using MarksMovies.WebServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace MarksMovies.Pages.Movies
{
    public class ExportModel : PageModel
    {

        private readonly WebExportService _service;

        public ExportModel(WebExportService Service)
        {
            _service = Service;
        }

        public enum ExportFileType
        {
            Json,
            CSV,
            Excel
        }

        [BindProperty]
        public ExportFileType FileTypeSelection { get; set; }

        [BindProperty]
        public string FileName { get; set; }

        public void OnGet()
        {

        }

        public async Task<FileResult> OnPostDownloadAsync()
        {
            string filename;
            
            switch (FileTypeSelection){
                case ExportFileType.Json:
                    {
                        filename = "Movies.json";
                        if (!string.IsNullOrEmpty(FileName))
                            filename = FileName;

                        byte[] bytes = System.Text.Encoding.UTF8.GetBytes(await _service.GetMoviesJsonAsync());
                        return File(bytes, "application/json", filename);
                    }
                case ExportFileType.Excel:
                    {
                        filename = "Movies.xlsx";
                        if (!string.IsNullOrEmpty(FileName))
                            filename = FileName;

                        return File(await _service.GetExcelFileAsync(), 
                                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                    filename);
                    }
                default:
                    return null;
            }
        }
    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MarksMovies.Models;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class IndexModel : PageModel
    {
        private readonly WebMovieIndexService _service;

        public IndexModel(WebMovieIndexService Service)
        {
            _service = Service;
        }

        public IList<Movie> Movie { get; set; }

        [BindProperty(SupportsGet =true)]
        public string SearchString { get; set; }
        

        [BindProperty(SupportsGet =true)]
        public GenreType MovieGenre { get; set; }

        public async Task OnGetAsync()
        {
            Movie = await _service.OnGetAsync(SearchString, MovieGenre);
        }



    }
}

MarksMovies.RazorPagesUI/Pages/Movies/RankMovies.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MarksMovies.Models;
using MarksMovies.WebServices;

namespace MarksMovies.Pages.Movies
{
    public class RankMoviesModel : PageModel
    {
        private readonly WebRankMovieService _service;

        public RankMoviesModel(WebRankMovieService Service)
        {
            _service = Service;
        }


        public IList<Movie> Movies { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Movies = await _service.GetRankedMoviesAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostUpdateRanksAsync(string ItemIds)
        {

            _ = await _service.UpdateRanksAsync(ItemIds);

            return RedirectToPage();
        }
    }
}

MarksMovies.RazorPagesUI/Pages/Movies/Create.cshtml
@page  "{tmdb_id:int?}"
@model MarksMovies.Pages.Movies.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />

<div class="container-fluid">
    <form method="post">
        <div class="row">
            <div class="col-md-3">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Movie.Title" class="control-label"></label>
                    <input asp-for="Movie.Title" class="form-control" />
                    <span asp-validation-for="Movie.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MovieOrTVShowSelection" class="control-label"></label>
                    <select asp-for="MovieOrTVShowSelection" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.MovieOrTVShow>()" class="form-control"></select>
                    <span asp-validation-for="MovieOrTVShowSelection" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedGenres" class="control-label"></label>
                    <select multiple="multiple" asp-for="SelectedGenres" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.GenreType>()" class="form-control"></select>
                    <span asp-validation-for="SelectedGenres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Rating" class="control-label"></label>
                    <select asp-for="Movie.Rating" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.Rating>()" class="form-control"></select>
                    <span asp-validation-for="Movie.Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.MediaType" class="control-label"></label>
                    <select asp-for="Movie.MediaType" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.DiscType>()" class="form-control"></select>
                    <span asp-validation-for="Movie.MediaType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.IMDB_ID" class="control-label"></label>
                    <input asp-for="Movie.IMDB_ID" class="form-control" />
                    <span asp-validation-for="Movie.IMDB_ID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Movie.Year" class="control-label"></label>
                    <input asp-for="@Model.Movie.Year" class="form-control" />
                    <span asp-validation-for="@Model.Movie.Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Movie.Season" class="control-label"></label>
                    <input asp-for="@Model.Movie.Season" class="form-control" />
                    <span asp-validation-for="@Model.Movie.Season" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Comments" class="control-label"></label>
                    <textarea rows="8" cols="40" asp-for="Movie.Comments" class="form-control"></textarea>
                    <span asp-validation-for="Movie.Comments" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="Movie.TMDB_ID" class="form-control" />
                    <button asp-page-handler="Create" class="btn btn-primary">Create</button>
                </div>

            </div>
            <div class="col">
                <div>
                    <span><button asp-page-handler="Fetch" class="btn btn-primary">Fetch TMDB Data</button></span>
                </div>
                <div class="container-fluid">
                    @if (Model.SearchMovies != null)
                    {
                        @if (Model.SearchMovies.total_results > 0)
                        {

                            foreach (var result in Model.SearchMovies.results)
                            {
                                <div class="row">
                                    <div class="col">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    @Html.DisplayFor(model => result.title)
                                                </h5>
                                                <h6 class="card-subtitle">
                                                    @Html.DisplayFor(model => result.release_date)
                                                </h6>
                                                <p class="card-text">
                                                    @Html.DisplayFor(model => result.overview)
                                                </p>


                                                <button asp-page-handler="Import" asp-route-tmdb_id="@result.id" class="btn btn-primary">Import</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }
                    @if (Model.SearchTV != null)
                    {
                        @if (Model.SearchTV.total_results > 0)
                        {

                            foreach (var result in Model.SearchTV.results)
                            {
                                <div class="row">
                                    <div class="col">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    @Html.DisplayFor(model => result.name)
                                                </h5>
                                                <h6 class="card-subtitle">
                                                    @Html.DisplayFor(model => result.first_air_date)
                                                </h6>
                                                <p class="card-text">
                                                    @Html.DisplayFor(model => result.overview)
                                                </p>


                                                <button asp-page-handler="Import" asp-route-tmdb_id="@result.id" class="btn btn-primary">Import</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }

                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarksMovies.RazorPagesUI/Pages/Movies/Edit.cshtml
@page "{id:int}/{TMDB_ID:int?}"
@model MarksMovies.Pages.Movies.EditModel

@{
    ViewData["Title"] = "Edit";
}


<div class="container-fluid">
    <h1>Edit</h1>

    <h4>Movie</h4>
    <hr />
    <div>
        <a href="@(Url.Content("~/Movies/Index") + "#" + Model.Movie.ID)">Back to List</a>
    </div>
    <form method="post">
        <div class="row">
            <div class="col-md-3">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Movie.ID" />
                <input type="hidden" asp-for="Movie.Rank" />
                <input type="hidden" asp-for="Movie.TMDB_ID" />
                <div class="form-group">
                    <label asp-for="Movie.Title" class="control-label"></label>
                    <input asp-for="Movie.Title" class="form-control" />
                    <span asp-validation-for="Movie.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MovieOrTVShowSelection" class="control-label"></label>
                    <select asp-for="MovieOrTVShowSelection" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.MovieOrTVShow>()" class="form-control"></select>
                    <span asp-validation-for="MovieOrTVShowSelection" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedGenres" class="control-label"></label>
                    <select multiple="multiple" asp-for="SelectedGenres" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.GenreType>()" class="form-control"></select>
                    <span asp-validation-for="SelectedGenres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Rating" class="control-label"></label>
                    <select asp-for="Movie.Rating" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.Rating>()" class="form-control"></select>
                    <span asp-validation-for="Movie.Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.MediaType" class="control-label"></label>
                    <select asp-for="Movie.MediaType" asp-items="@Html.GetEnumSelectList<MarksMovies.Models.DiscType>()" class="form-control"></select>
                    <span asp-validation-for="Movie.MediaType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.IMDB_ID" class="control-label"></label>
                    <input asp-for="Movie.IMDB_ID" class="form-control" />
                    <span asp-validation-for="Movie.IMDB_ID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Movie.Year" class="control-label"></label>
                    <input asp-for="@Model.Movie.Year" class="form-control" />
                    <span asp-validation-for="@Model.Movie.Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Movie.Season" class="control-label"></label>
                    <input asp-for="@Model.Movie.Season" class="form-control" />
                    <span asp-validation-for="@Model.Movie.Season" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Comments" class="control-label"></label>
                    <textarea rows="8" cols="40" asp-for="Movie.Comments" class="form-control"></textarea>
                    <span asp-validation-for="Movie.Comments" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button asp-page-handler="Edit" class="btn btn-primary">Save</button>
                </div>

            </div>
            <div class="col">
                <div>
                    <span><button asp-page-handler="Fetch" class="btn btn-primary">Fetch TMDB Data</button></span>
                </div>
                <div class="container-fluid">
                    @if (Model.SearchMovies != null)
                    {
                        @if (Model.SearchMovies.total_results > 0)
                        {

                            foreach (var result in Model.SearchMovies.results)
                            {
                                <div class="row">
                                    <div class="col">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    @Html.DisplayFor(model => result.title)
                                                </h5>
                                                <h6 class="card-subtitle">
                                                    @Html.DisplayFor(model => result.release_date)
                                                </h6>
                                                <p class="card-text">
                                                    @Html.DisplayFor(model => result.overview)
                                                </p>


                                                <button asp-page-handler="Import" asp-route-tmdb_id="@result.id" class="btn btn-primary">Import</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }

                        }
                    }
                    @if (Model.SearchTV != null)
                    {
                        @if (Model.SearchTV.total_results > 0)
                        {

                            foreach (var result in Model.SearchTV.results)
                            {
                                <div class="row">
                                    <div class="col">
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    @Html.DisplayFor(model => result.name)
                                                </h5>
                                                <h6 class="card-subtitle">
                                                    @Html.DisplayFor(model => result.first_air_date)
                                                </h6>
                                                <p class="card-text">
                                                    @Html.DisplayFor(model => result.overview)
                                                </p>
                                                <button asp-page-handler="Import" asp-route-tmdb_id="@result.id" class="btn btn-primary">Import</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }


                </div>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarksMovies.RazorPagesUI/Pages/Movies/Export.cshtml
@page
@model MarksMovies.Pages.Movies.ExportModel
@{
    ViewData["Title"] = "Export";
}

<h1>Export</h1>

<div>
    <a href="@(Url.Content("~/Movies/Index"))">Back to List</a>
</div>

<div>
    <form method="post">
        <div class="container-fluid">
            <div class="form-group row">
                <div class="row">
                    <div class="col-md-auto">
                        <label asp-for="FileTypeSelection" class="control-label"></label>
                        <select asp-for="FileTypeSelection" asp-items="@Html.GetEnumSelectList<ExportModel.ExportFileType>()" class="form-control"></select>
                        <span asp-validation-for="FileTypeSelection" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="row">
                    <div class="col-md-auto">
                        <label asp-for="FileName" class="control-label"></label>
                    </div>
                    <div class="col-auto"> </div>
                </div>
                <div class="row">
                    <div class="col-md-auto">
                        <input asp-for="FileName" type="text" class="form-control" />
                        <span asp-validation-for="FileName" class="text-danger"></span>
                    </div>
                    <div class="col-auto">
                        <button asp-page-handler="Download" class="btn btn-primary">Download</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>